# Generated by Django 5.0.14 on 2025-11-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("provider", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("undergraduate", "Undergraduate"),
                            ("graduate", "Graduate"),
                            ("doctoral", "Doctoral"),
                            ("postdoctoral", "Postdoctoral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("disciplines", models.JSONField(default=list)),
                ("amount", models.CharField(max_length=200)),
                ("deadline", models.DateField()),
                ("description", models.TextField()),
                ("eligibility", models.JSONField(default=list)),
                ("application_url", models.URLField()),
                (
                    "funded",
                    models.CharField(
                        choices=[
                            ("fully", "Fully Funded"),
                            ("partial", "Partially Funded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["deadline"],
                "indexes": [
                    models.Index(
                        fields=["deadline"], name="scholarship_deadlin_f24616_idx"
                    ),
                    models.Index(fields=["level"], name="scholarship_level_f4fd45_idx"),
                ],
            },
        ),
    ]
