# Generated by Django 5.0.14 on 2025-11-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarship",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
