# Generated by Django 5.0.14 on 2025-11-09 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("manufacturing", "Manufacturing Hub"),
                            ("tech_park", "Technology Park"),
                            ("industrial_estate", "Industrial Estate"),
                            ("special_economic", "Special Economic Zone"),
                            ("cluster", "Industry Cluster"),
                        ],
                        max_length=30,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("punjab", "Punjab"),
                            ("sindh", "Sindh"),
                            ("kpk", "Khyber Pakhtunkhwa"),
                            ("balochistan", "Balochistan"),
                            ("ajk", "Azad Jammu & Kashmir"),
                            ("gilgit", "Gilgit-Baltistan"),
                            ("islamabad", "Islamabad Capital Territory"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("description", models.TextField()),
                (
                    "primary_industries",
                    models.TextField(
                        help_text="Primary engineering industries (comma-separated)"
                    ),
                ),
                ("number_of_companies", models.PositiveIntegerField(default=0)),
                ("approximate_employment", models.PositiveIntegerField(default=0)),
                (
                    "infrastructure",
                    models.TextField(
                        help_text="Available infrastructure and facilities"
                    ),
                ),
                (
                    "utilities",
                    models.TextField(help_text="Power, water, gas availability"),
                ),
                (
                    "established_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("managing_authority", models.CharField(max_length=200)),
                ("website", models.URLField(blank=True)),
                ("contact_info", models.TextField(blank=True)),
                (
                    "engineering_density",
                    models.CharField(
                        choices=[
                            ("high", "High (50+ companies)"),
                            ("medium", "Medium (20-50 companies)"),
                            ("low", "Low (<20 companies)"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "location_industry_zones",
                "ordering": ["province", "city"],
                "indexes": [
                    models.Index(
                        fields=["province", "city"],
                        name="location_in_provinc_adfa45_idx",
                    ),
                    models.Index(
                        fields=["zone_type"], name="location_in_zone_ty_e50844_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("consultancy", "Engineering Consultancy"),
                            ("testing_lab", "Testing Laboratory"),
                            ("design_firm", "Design Firm"),
                            ("inspection", "Inspection Services"),
                            ("certification", "Certification Body"),
                            ("surveying", "Surveying Services"),
                            ("association", "Professional Association"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "disciplines_served",
                    models.TextField(
                        help_text="Engineering disciplines (comma-separated)"
                    ),
                ),
                ("services_offered", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("serves_nationwide", models.BooleanField(default=False)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "accreditations",
                    models.TextField(
                        blank=True,
                        help_text="Relevant accreditations (PSQCA, ISO, etc.)",
                    ),
                ),
                (
                    "established_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "pec_registered",
                    models.BooleanField(
                        default=False,
                        help_text="Registered with Pakistan Engineering Council",
                    ),
                ),
                (
                    "pec_registration_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("verified", models.BooleanField(default=False)),
                ("rating_sum", models.PositiveIntegerField(default=0)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "location_professional_services",
                "ordering": ["city", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("review", models.TextField()),
                (
                    "service_used",
                    models.CharField(
                        help_text="Which service did you use?", max_length=200
                    ),
                ),
                ("project_type", models.CharField(blank=True, max_length=200)),
                ("pros", models.TextField()),
                ("cons", models.TextField()),
                ("would_recommend", models.BooleanField()),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="location.professionalservice",
                    ),
                ),
            ],
            options={
                "db_table": "location_service_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="professionalservice",
            index=models.Index(
                fields=["service_type", "city"], name="location_pr_service_ffeba0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="professionalservice",
            index=models.Index(
                fields=["pec_registered"], name="location_pr_pec_reg_34c4dc_idx"
            ),
        ),
    ]
