# Generated by Django 5.0.14 on 2025-11-08 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("discipline", models.CharField(max_length=100)),
                ("overview", models.TextField()),
                ("skills", models.JSONField(default=list)),
                ("industries", models.JSONField(default=list)),
                ("salary_range", models.CharField(max_length=100)),
                ("growth_outlook", models.TextField()),
                ("education_required", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("current_position", models.CharField(max_length=100)),
                ("years_of_experience", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "career_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to="careers.careerpath",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Experience Stories",
                "ordering": ["-created_at"],
            },
        ),
    ]
