# Generated by Django 5.0.14 on 2025-11-08 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full-time"),
                            ("part-time", "Part-time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        max_length=20,
                    ),
                ),
                ("discipline", models.CharField(max_length=100)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("requirements", models.JSONField(default=list)),
                ("salary", models.CharField(blank=True, max_length=100)),
                ("application_url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                ("posted_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-posted_date"],
                "indexes": [
                    models.Index(
                        fields=["-posted_date"], name="jobs_job_posted__bd758d_idx"
                    ),
                    models.Index(
                        fields=["job_type"], name="jobs_job_job_typ_f6c220_idx"
                    ),
                    models.Index(
                        fields=["discipline"], name="jobs_job_discipl_65cf2b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("reviewing", "Under Review"),
                            ("interview", "Interview Scheduled"),
                            ("offer", "Offer Received"),
                            ("rejected", "Rejected"),
                            ("accepted", "Accepted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
                "unique_together": {("user", "job")},
            },
        ),
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at"],
                "unique_together": {("user", "job")},
            },
        ),
    ]
