# Generated by Django 5.0.14 on 2025-11-09 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., 'Software Engineer Resume'", max_length=200
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=100)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                ("summary", models.TextField()),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("modern", "Modern"),
                            ("classic", "Classic"),
                            ("technical", "Technical"),
                            ("minimalist", "Minimalist"),
                        ],
                        default="modern",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "career_tools_resumes",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("currently_studying", models.BooleanField(default=False)),
                ("gpa", models.CharField(blank=True, max_length=20)),
                ("achievements", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="career_tools.resume",
                    ),
                ),
            ],
            options={
                "db_table": "career_tools_resume_education",
                "ordering": ["order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ResumeExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("currently_working", models.BooleanField(default=False)),
                ("responsibilities", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience",
                        to="career_tools.resume",
                    ),
                ),
            ],
            options={
                "db_table": "career_tools_resume_experience",
                "ordering": ["order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ResumeProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("technologies", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="career_tools.resume",
                    ),
                ),
            ],
            options={
                "db_table": "career_tools_resume_projects",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ResumeSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="e.g., Programming Languages, Tools, etc.",
                        max_length=100,
                    ),
                ),
                ("skills", models.TextField(help_text="Comma-separated skills")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="career_tools.resume",
                    ),
                ),
            ],
            options={
                "db_table": "career_tools_resume_skills",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CareerTransitionStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("from_discipline", models.CharField(max_length=100)),
                ("to_discipline", models.CharField(max_length=100)),
                ("from_role", models.CharField(max_length=200)),
                ("to_role", models.CharField(max_length=200)),
                (
                    "transition_type",
                    models.CharField(
                        choices=[
                            ("discipline_switch", "Switched Engineering Discipline"),
                            ("academia_to_industry", "Academia to Industry"),
                            ("industry_to_academia", "Industry to Academia"),
                            ("pakistan_to_abroad", "Pakistan to Abroad"),
                            ("abroad_to_pakistan", "Abroad to Pakistan"),
                            ("startup_journey", "Started Own Company"),
                        ],
                        max_length=30,
                    ),
                ),
                ("years_in_previous_field", models.PositiveIntegerField()),
                (
                    "transition_duration_months",
                    models.PositiveIntegerField(
                        help_text="How long did the transition take?"
                    ),
                ),
                (
                    "motivation",
                    models.TextField(help_text="Why did you make this transition?"),
                ),
                ("challenges_faced", models.TextField()),
                (
                    "how_you_did_it",
                    models.TextField(help_text="Steps you took to make the transition"),
                ),
                (
                    "advice",
                    models.TextField(
                        help_text="Advice for others considering similar transition"
                    ),
                ),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transition_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Career Transition Stories",
                "db_table": "career_tools_transition_stories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transition_type"],
                        name="career_tool_transit_7a8efb_idx",
                    ),
                    models.Index(
                        fields=["-helpful_count"], name="career_tool_helpful_d21bc8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalaryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=200)),
                ("discipline", models.CharField(max_length=100)),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("startup", "Startup (1-50)"),
                            ("small", "Small (51-200)"),
                            ("medium", "Medium (201-1000)"),
                            ("large", "Large (1000+)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("local", "Local Pakistani Company"),
                            ("multinational", "Multinational"),
                            ("remote_foreign", "Remote for Foreign Company"),
                        ],
                        max_length=20,
                    ),
                ),
                ("years_of_experience", models.PositiveIntegerField()),
                ("city", models.CharField(max_length=100)),
                (
                    "base_salary_monthly",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "bonus_annual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("stock_options", models.BooleanField(default=False)),
                ("health_insurance", models.BooleanField(default=False)),
                ("provident_fund", models.BooleanField(default=False)),
                ("paid_leave_days", models.PositiveIntegerField(default=0)),
                ("work_from_home", models.BooleanField(default=False)),
                (
                    "satisfaction_rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Overall job satisfaction",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data_year", models.PositiveIntegerField()),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "career_tools_salary_data",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["position", "city"],
                        name="career_tool_positio_88797f_idx",
                    ),
                    models.Index(
                        fields=["discipline"], name="career_tool_discipl_88fb57_idx"
                    ),
                    models.Index(
                        fields=["years_of_experience"],
                        name="career_tool_years_o_1e9047_idx",
                    ),
                ],
            },
        ),
    ]
