# Generated by Django 5.0.14 on 2025-11-09 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "competition_type",
                    models.CharField(
                        choices=[
                            ("robotics", "Robotics"),
                            ("hackathon", "Hackathon"),
                            ("design", "Design Challenge"),
                            ("coding", "Coding Competition"),
                            ("innovation", "Innovation Contest"),
                            ("case_study", "Case Study"),
                        ],
                        max_length=20,
                    ),
                ),
                ("organizer", models.CharField(max_length=200)),
                ("discipline", models.CharField(blank=True, max_length=100)),
                (
                    "eligible_levels",
                    models.CharField(
                        help_text="Undergraduate, Graduate, etc. (comma-separated)",
                        max_length=100,
                    ),
                ),
                ("team_size_min", models.PositiveIntegerField(default=1)),
                ("team_size_max", models.PositiveIntegerField()),
                ("registration_start", models.DateField()),
                ("registration_deadline", models.DateField()),
                ("event_start_date", models.DateField()),
                ("event_end_date", models.DateField()),
                ("location", models.CharField(max_length=200)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("in_person", "In-Person"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prizes", models.TextField(help_text="Prize details")),
                (
                    "registration_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("registration_url", models.URLField()),
                ("website", models.URLField(blank=True)),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "projects_competitions",
                "ordering": ["registration_deadline"],
            },
        ),
        migrations.CreateModel(
            name="CompetitionParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(blank=True, max_length=200)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.competition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_competition_participation",
                "unique_together": {("competition", "user")},
            },
        ),
        migrations.AddField(
            model_name="competition",
            name="participants",
            field=models.ManyToManyField(
                related_name="competitions_joined",
                through="projects.CompetitionParticipation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="OpenSourceProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("repository_url", models.URLField()),
                ("primary_language", models.CharField(max_length=50)),
                ("license", models.CharField(max_length=50)),
                ("topics", models.TextField(help_text="Comma-separated topics/tags")),
                ("looking_for_contributors", models.BooleanField(default=True)),
                (
                    "skill_level_required",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner Friendly"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contribution_guidelines", models.TextField()),
                (
                    "good_first_issues",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of good first issues"
                    ),
                ),
                ("contributors_count", models.PositiveIntegerField(default=0)),
                ("stars", models.PositiveIntegerField(default=0)),
                ("forks", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "maintainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="os_projects_maintained",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pakistani_contributors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="os_projects_contributed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_open_source",
                "ordering": ["-stars"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("final_year", "Final Year Project"),
                            ("personal", "Personal Project"),
                            ("hackathon", "Hackathon Project"),
                            ("research", "Research Project"),
                            ("open_source", "Open Source"),
                            ("commercial", "Commercial Project"),
                        ],
                        max_length=20,
                    ),
                ),
                ("discipline", models.CharField(max_length=100)),
                ("university", models.CharField(blank=True, max_length=200)),
                ("completion_date", models.DateField()),
                (
                    "technologies_used",
                    models.TextField(help_text="Comma-separated list"),
                ),
                ("problem_statement", models.TextField()),
                ("solution_approach", models.TextField()),
                ("key_features", models.TextField()),
                ("challenges_faced", models.TextField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("demo_url", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("documentation_url", models.URLField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="projects/thumbnails/"),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("featured", models.BooleanField(default=False)),
                ("tags", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects_liked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WinningProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.CharField(max_length=200)),
                ("team_name", models.CharField(max_length=200)),
                ("team_members", models.TextField()),
                ("university", models.CharField(blank=True, max_length=200)),
                ("prize", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("video_url", models.URLField(blank=True)),
                ("year", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winners",
                        to="projects.competition",
                    ),
                ),
            ],
            options={
                "db_table": "projects_winning_projects",
                "ordering": ["-year"],
            },
        ),
        migrations.AddIndex(
            model_name="competition",
            index=models.Index(
                fields=["competition_type"], name="projects_co_competi_39f9dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="competition",
            index=models.Index(
                fields=["registration_deadline"], name="projects_co_registr_fc2560_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opensourceproject",
            index=models.Index(
                fields=["primary_language"], name="projects_op_primary_04981f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opensourceproject",
            index=models.Index(
                fields=["looking_for_contributors"],
                name="projects_op_looking_d15bea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["discipline"], name="projects_pr_discipl_a01fde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["project_type"], name="projects_pr_project_ad3eba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["-created_at"], name="projects_pr_created_5acda1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["-views"], name="projects_pr_views_3af0ae_idx"),
        ),
        migrations.AddIndex(
            model_name="winningproject",
            index=models.Index(fields=["-year"], name="projects_wi_year_3bd402_idx"),
        ),
    ]
