# Generated by Django 5.0.14 on 2025-11-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("professional", "Professional"),
                    ("expert", "Expert"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                default="student",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
