# Generated by Django 5.0.14 on 2025-11-09 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "conference_type",
                    models.CharField(
                        choices=[
                            ("conference", "Conference"),
                            ("workshop", "Workshop"),
                            ("symposium", "Symposium"),
                            ("seminar", "Seminar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("discipline", models.CharField(max_length=100)),
                ("topics", models.TextField(help_text="Comma-separated topics")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("location", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=100)),
                ("virtual_option", models.BooleanField(default=False)),
                ("accepts_papers", models.BooleanField(default=True)),
                ("paper_submission_deadline", models.DateField(blank=True, null=True)),
                ("notification_date", models.DateField(blank=True, null=True)),
                ("camera_ready_deadline", models.DateField(blank=True, null=True)),
                (
                    "early_registration_deadline",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "registration_fee",
                    models.DecimalField(
                        decimal_places=2, help_text="In USD", max_digits=10
                    ),
                ),
                ("student_discount", models.BooleanField(default=False)),
                ("website", models.URLField()),
                ("submission_portal", models.URLField(blank=True)),
                (
                    "pakistan_friendly",
                    models.BooleanField(
                        default=False, help_text="Easy visa/affordable for Pakistanis"
                    ),
                ),
                ("travel_grants_available", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "marketplace_conferences",
                "ordering": ["paper_submission_deadline"],
                "indexes": [
                    models.Index(
                        fields=["discipline"], name="marketplace_discipl_256cbb_idx"
                    ),
                    models.Index(
                        fields=["paper_submission_deadline"],
                        name="marketplace_paper_s_05d8d0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FreelanceProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("design", "Design & CAD"),
                            ("analysis", "Analysis & Simulation"),
                            ("development", "Software Development"),
                            ("consulting", "Technical Consulting"),
                            ("documentation", "Technical Documentation"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("discipline", models.CharField(max_length=100)),
                (
                    "budget_min",
                    models.DecimalField(
                        decimal_places=2, help_text="In PKR", max_digits=10
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        decimal_places=2, help_text="In PKR", max_digits=10
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="e.g., '2 weeks', '1 month'", max_length=100
                    ),
                ),
                (
                    "required_skills",
                    models.TextField(help_text="Comma-separated skills"),
                ),
                (
                    "experience_required",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open for Proposals"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "location_required",
                    models.CharField(
                        blank=True, help_text="If on-site work needed", max_length=100
                    ),
                ),
                ("remote_ok", models.BooleanField(default=True)),
                ("proposals_count", models.PositiveIntegerField(default=0)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateField()),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelance_projects_posted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_freelance_projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FreelanceProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_letter", models.TextField()),
                (
                    "proposed_budget",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("proposed_timeline", models.CharField(max_length=100)),
                ("portfolio_links", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelance_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="marketplace.freelanceproject",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_freelance_proposals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchCollaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("discipline", models.CharField(max_length=100)),
                ("research_area", models.CharField(max_length=200)),
                ("keywords", models.TextField(help_text="Comma-separated keywords")),
                (
                    "collaboration_type",
                    models.CharField(
                        choices=[
                            ("co_author", "Looking for Co-Authors"),
                            ("data_sharing", "Data Sharing"),
                            ("equipment_sharing", "Equipment/Lab Sharing"),
                            ("expertise", "Need Specific Expertise"),
                            ("funding_partner", "Looking for Funding Partner"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "looking_for",
                    models.TextField(
                        help_text="What kind of collaborators are you looking for?"
                    ),
                ),
                ("expected_commitment", models.TextField()),
                ("timeline", models.CharField(max_length=100)),
                ("institution", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                ("remote_collaboration_ok", models.BooleanField(default=True)),
                ("funding_available", models.BooleanField(default=False)),
                ("funding_details", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_collaborations_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interested_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="research_interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_research_collaborations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="freelanceproject",
            index=models.Index(
                fields=["status", "-created_at"], name="marketplace_status_46da7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="freelanceproject",
            index=models.Index(
                fields=["discipline"], name="marketplace_discipl_d9c22a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="freelanceproposal",
            unique_together={("project", "freelancer")},
        ),
        migrations.AddIndex(
            model_name="researchcollaboration",
            index=models.Index(
                fields=["discipline"], name="marketplace_discipl_a008f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchcollaboration",
            index=models.Index(
                fields=["is_active"], name="marketplace_is_acti_1c2661_idx"
            ),
        ),
    ]
