# Generated by Django 5.0.14 on 2025-11-09 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="Tell potential mentees about your background and what you can help with"
                    ),
                ),
                ("years_of_experience", models.PositiveIntegerField()),
                ("current_position", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                (
                    "expertise_areas",
                    models.TextField(
                        help_text="Comma-separated list of expertise areas"
                    ),
                ),
                (
                    "max_mentees",
                    models.PositiveIntegerField(
                        default=3, help_text="Maximum number of mentees at once"
                    ),
                ),
                ("available_for_mentorship", models.BooleanField(default=True)),
                (
                    "mentorship_type",
                    models.CharField(
                        choices=[
                            ("one_on_one", "One-on-One"),
                            ("group", "Group"),
                            ("both", "Both"),
                        ],
                        default="one_on_one",
                        max_length=20,
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mentorship_mentor_profiles",
            },
        ),
        migrations.CreateModel(
            name="MentorshipRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Tell the mentor why you want their guidance"
                    ),
                ),
                (
                    "goals",
                    models.TextField(help_text="What are your mentorship goals?"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_requests",
                        to="mentorship.mentorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "mentorship_requests",
            },
        ),
        migrations.CreateModel(
            name="MentorshipSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("topics_discussed", models.TextField()),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Session notes (visible to both parties)"
                    ),
                ),
                (
                    "action_items",
                    models.TextField(blank=True, help_text="Action items for mentee"),
                ),
                (
                    "mentee_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Mentee's rating of the session",
                        null=True,
                    ),
                ),
                (
                    "mentor_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Mentor's rating of the session",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="mentorship.mentorshiprequest",
                    ),
                ),
            ],
            options={
                "db_table": "mentorship_sessions",
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="SkillAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Skills"),
                            ("soft", "Soft Skills"),
                            ("tools", "Tools & Software"),
                            ("domain", "Domain Knowledge"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "current_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Beginner"),
                            (2, "Elementary"),
                            (3, "Intermediate"),
                            (4, "Advanced"),
                            (5, "Expert"),
                        ]
                    ),
                ),
                (
                    "target_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Beginner"),
                            (2, "Elementary"),
                            (3, "Intermediate"),
                            (4, "Advanced"),
                            (5, "Expert"),
                        ]
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="How did you acquire this skill? What projects have you used it in?",
                    ),
                ),
                ("last_used", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mentorship_skill_assessments",
            },
        ),
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("subject", models.CharField(max_length=100)),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("computer_science", "Computer Science"),
                            ("electrical", "Electrical Engineering"),
                            ("mechanical", "Mechanical Engineering"),
                            ("civil", "Civil Engineering"),
                            ("chemical", "Chemical Engineering"),
                            ("software", "Software Engineering"),
                            ("biomedical", "Biomedical Engineering"),
                            ("aerospace", "Aerospace Engineering"),
                            ("industrial", "Industrial Engineering"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("max_members", models.PositiveIntegerField(default=10)),
                (
                    "meeting_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-Weekly"),
                            ("monthly", "Monthly"),
                            ("flexible", "Flexible"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "meeting_format",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("in_person", "In-Person"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="For in-person/hybrid groups",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_groups_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mentorship_study_groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_moderator", models.BooleanField(default=False)),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.studygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mentorship_study_group_memberships",
            },
        ),
        migrations.AddField(
            model_name="studygroup",
            name="members",
            field=models.ManyToManyField(
                related_name="study_groups",
                through="mentorship.StudyGroupMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="InterviewExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("computer_science", "Computer Science"),
                            ("electrical", "Electrical Engineering"),
                            ("mechanical", "Mechanical Engineering"),
                            ("civil", "Civil Engineering"),
                            ("chemical", "Chemical Engineering"),
                            ("software", "Software Engineering"),
                            ("biomedical", "Biomedical Engineering"),
                            ("aerospace", "Aerospace Engineering"),
                            ("industrial", "Industrial Engineering"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior Level"),
                            ("lead", "Lead/Principal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("interview_date", models.DateField()),
                (
                    "location",
                    models.CharField(help_text="City, Pakistan", max_length=100),
                ),
                (
                    "interview_process",
                    models.TextField(
                        help_text="Describe the stages of the interview process"
                    ),
                ),
                (
                    "technical_questions",
                    models.TextField(blank=True, help_text="Technical questions asked"),
                ),
                (
                    "behavioral_questions",
                    models.TextField(
                        blank=True, help_text="Behavioral questions asked"
                    ),
                ),
                (
                    "tips",
                    models.TextField(blank=True, help_text="Your tips for others"),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("offered", "Offer Received"),
                            ("rejected", "Rejected"),
                            ("ongoing", "Still In Process"),
                            ("declined", "Declined Offer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="How difficult was the interview? (1=Easy, 5=Very Hard)",
                    ),
                ),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_experiences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mentorship_interview_experiences",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company"], name="mentorship__company_da7ad9_idx"
                    ),
                    models.Index(
                        fields=["discipline"], name="mentorship__discipl_a27745_idx"
                    ),
                    models.Index(
                        fields=["-helpful_count"], name="mentorship__helpful_43683b_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="mentorship__created_d3ee07_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mentorprofile",
            index=models.Index(
                fields=["available_for_mentorship"],
                name="mentorship__availab_78a4fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mentorprofile",
            index=models.Index(
                fields=["-created_at"], name="mentorship__created_5b0eba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mentorshiprequest",
            index=models.Index(fields=["status"], name="mentorship__status_9d5f67_idx"),
        ),
        migrations.AddIndex(
            model_name="mentorshiprequest",
            index=models.Index(
                fields=["-created_at"], name="mentorship__created_a0c7b6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mentorshiprequest",
            unique_together={("mentee", "mentor")},
        ),
        migrations.AddIndex(
            model_name="mentorshipsession",
            index=models.Index(
                fields=["-session_date"], name="mentorship__session_6a01d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skillassessment",
            index=models.Index(
                fields=["user", "category"], name="mentorship__user_id_aa27db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skillassessment",
            index=models.Index(
                fields=["-updated_at"], name="mentorship__updated_5ee239_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skillassessment",
            unique_together={("user", "skill_name")},
        ),
        migrations.AddIndex(
            model_name="studygroupmembership",
            index=models.Index(
                fields=["study_group", "-joined_at"],
                name="mentorship__study_g_fd1d4b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studygroupmembership",
            unique_together={("study_group", "user")},
        ),
        migrations.AddIndex(
            model_name="studygroup",
            index=models.Index(
                fields=["discipline", "is_active"],
                name="mentorship__discipl_8c004f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studygroup",
            index=models.Index(
                fields=["-created_at"], name="mentorship__created_fc552e_idx"
            ),
        ),
    ]
