# Generated by Django 5.0.14 on 2025-11-12 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("mentorship", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="interviewexperience",
            new_name="mentorship__company_6475e2_idx",
            old_name="mentorship__company_da7ad9_idx",
        ),
        migrations.AddField(
            model_name="interviewexperience",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Enter company name if not found in the company list",
                max_length=200,
                verbose_name="Company Name (if not in system)",
            ),
        ),
        migrations.AlterField(
            model_name="interviewexperience",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_experiences",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
    ]
