# Generated by Django 5.0.14 on 2025-11-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StartupResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("funding", "Funding"),
                            ("incubator", "Incubator"),
                            ("accelerator", "Accelerator"),
                            ("mentorship", "Mentorship"),
                            ("legal", "Legal"),
                            ("technical", "Technical"),
                            ("guide", "Guide"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("provider", models.CharField(max_length=200)),
                ("link", models.URLField(blank=True)),
                ("eligibility", models.JSONField(blank=True, default=list)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "title"],
            },
        ),
    ]
