# Generated by Django 5.0.14 on 2025-11-09 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "hub_type",
                    models.CharField(
                        choices=[
                            ("coworking", "Coworking Space"),
                            ("makerspace", "Makerspace/Fab Lab"),
                            ("library", "University Library"),
                            ("cafe", "Study Cafe"),
                            ("incubator", "Incubator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "facilities",
                    models.TextField(
                        help_text="Available facilities (comma-separated)"
                    ),
                ),
                ("for_students", models.BooleanField(default=True)),
                ("for_professionals", models.BooleanField(default=True)),
                ("open_to_public", models.BooleanField(default=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("operating_hours", models.TextField()),
                ("pricing_info", models.TextField()),
                ("rating_sum", models.PositiveIntegerField(default=0)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "community_local_hubs",
                "ordering": ["city", "name"],
                "indexes": [
                    models.Index(
                        fields=["city", "hub_type"], name="community_l_city_f8c723_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SuccessStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("featured_person", models.CharField(max_length=200)),
                ("current_position", models.CharField(max_length=200)),
                ("current_company", models.CharField(blank=True, max_length=200)),
                (
                    "story_type",
                    models.CharField(
                        choices=[
                            ("startup_success", "Startup Success"),
                            ("innovation", "Innovation Story"),
                            ("return_to_pakistan", "Returned to Pakistan"),
                            ("career_achievement", "Career Achievement"),
                            ("social_impact", "Social Impact"),
                        ],
                        max_length=30,
                    ),
                ),
                ("education", models.TextField()),
                ("journey", models.TextField(help_text="Their journey and story")),
                ("challenges_overcome", models.TextField()),
                ("key_lessons", models.TextField()),
                ("advice", models.TextField()),
                ("photo", models.ImageField(blank=True, upload_to="success_stories/")),
                ("video_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("featured", models.BooleanField(default=False)),
                ("views", models.PositiveIntegerField(default=0)),
                ("inspiring_count", models.PositiveIntegerField(default=0)),
                ("published_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Success Stories",
                "db_table": "community_success_stories",
                "ordering": ["-published_date"],
                "indexes": [
                    models.Index(
                        fields=["story_type"], name="community_s_story_t_d95854_idx"
                    ),
                    models.Index(
                        fields=["-published_date"],
                        name="community_s_publish_48078a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WikiArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("how_to", "How-To Guides"),
                            ("procedure", "Government Procedures"),
                            ("certification", "Certifications"),
                            ("city_guide", "City Guides"),
                            ("career", "Career Guides"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "tags",
                    models.CharField(help_text="Comma-separated tags", max_length=200),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("views", models.PositiveIntegerField(default=0)),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_articles_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contributors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wiki_articles_contributed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_articles",
                    models.ManyToManyField(blank=True, to="community.wikiarticle"),
                ),
            ],
            options={
                "db_table": "community_wiki_articles",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WikiRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("edit_summary", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="community.wikiarticle",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "community_wiki_revisions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("content", models.TextField()),
                ("source", models.CharField(max_length=200)),
                ("source_url", models.URLField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("policy", "Policy & Regulations"),
                            ("infrastructure", "Infrastructure Projects"),
                            ("technology", "Technology Trends"),
                            ("education", "Engineering Education"),
                            ("jobs", "Job Market"),
                            ("innovation", "Innovations"),
                        ],
                        max_length=30,
                    ),
                ),
                ("discipline", models.CharField(blank=True, max_length=100)),
                (
                    "tags",
                    models.CharField(help_text="Comma-separated tags", max_length=200),
                ),
                ("thumbnail", models.ImageField(blank=True, upload_to="news/")),
                ("views", models.PositiveIntegerField(default=0)),
                ("published_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_articles_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "community_news_articles",
                "ordering": ["-published_date"],
                "indexes": [
                    models.Index(
                        fields=["category", "-published_date"],
                        name="community_n_categor_b90247_idx",
                    ),
                    models.Index(
                        fields=["-published_date"],
                        name="community_n_publish_8dc28b_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="wikiarticle",
            index=models.Index(
                fields=["category"], name="community_w_categor_37aaf7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wikiarticle",
            index=models.Index(fields=["slug"], name="community_w_slug_b6b66c_idx"),
        ),
    ]
