# Generated by Django 5.0.14 on 2025-11-09 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchSupervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Prof., Dr., etc.", max_length=50),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("university", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=100)),
                (
                    "position",
                    models.CharField(
                        help_text="Professor, Associate Professor, etc.", max_length=100
                    ),
                ),
                (
                    "research_interests",
                    models.TextField(help_text="Research areas (comma-separated)"),
                ),
                ("discipline", models.CharField(max_length=100)),
                ("expertise_keywords", models.TextField()),
                ("accepting_students", models.BooleanField(default=True)),
                (
                    "accepting_levels",
                    models.CharField(
                        help_text="MS, PhD (comma-separated)", max_length=100
                    ),
                ),
                ("current_students_count", models.PositiveIntegerField(default=0)),
                ("max_students", models.PositiveIntegerField(default=5)),
                ("bio", models.TextField()),
                ("education", models.TextField()),
                ("publications_count", models.PositiveIntegerField(default=0)),
                ("h_index", models.PositiveIntegerField(blank=True, null=True)),
                ("preferred_contact_method", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("office_hours", models.TextField(blank=True)),
                ("google_scholar_url", models.URLField(blank=True)),
                ("researchgate_url", models.URLField(blank=True)),
                ("university_profile_url", models.URLField(blank=True)),
                (
                    "response_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "academic_research_supervisors",
                "ordering": ["university", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="SupervisorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("current", "Current Student"),
                            ("former", "Former Student"),
                            ("applicant", "Prospective Student"),
                        ],
                        max_length=20,
                    ),
                ),
                ("degree_level", models.CharField(max_length=20)),
                (
                    "years_supervised",
                    models.PositiveIntegerField(help_text="Duration in years"),
                ),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "availability",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "guidance_quality",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "research_environment",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("pros", models.TextField()),
                ("cons", models.TextField()),
                ("advice", models.TextField(help_text="Advice for future students")),
                ("would_recommend", models.BooleanField()),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("verified_student", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="academic.researchsupervisor",
                    ),
                ),
            ],
            options={
                "db_table": "academic_supervisor_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThesisTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("abstract", models.TextField()),
                ("discipline", models.CharField(max_length=100)),
                (
                    "degree_level",
                    models.CharField(
                        choices=[
                            ("undergraduate", "Undergraduate"),
                            ("masters", "Masters"),
                            ("phd", "PhD"),
                        ],
                        max_length=20,
                    ),
                ),
                ("university", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=200)),
                ("supervisor", models.CharField(max_length=200)),
                ("completion_year", models.PositiveIntegerField()),
                ("keywords", models.TextField(help_text="Comma-separated keywords")),
                ("methodology", models.TextField()),
                ("key_findings", models.TextField(blank=True)),
                ("future_work", models.TextField(blank=True)),
                ("full_text_url", models.URLField(blank=True)),
                ("pdf_file", models.FileField(blank=True, upload_to="theses/")),
                ("is_public", models.BooleanField(default=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("downloads", models.PositiveIntegerField(default=0)),
                ("citations", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thesis_topics_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "academic_thesis_topics",
                "ordering": ["-completion_year"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("authors", models.TextField()),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("journal", "Journal Article"),
                            ("conference", "Conference Paper"),
                            ("thesis", "Thesis"),
                            ("book", "Book/Chapter"),
                            ("preprint", "Preprint"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        help_text="Journal/Conference name", max_length=300
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("volume", models.CharField(blank=True, max_length=50)),
                ("pages", models.CharField(blank=True, max_length=50)),
                ("abstract", models.TextField()),
                ("keywords", models.TextField()),
                ("discipline", models.CharField(max_length=100)),
                ("doi", models.CharField(blank=True, max_length=100)),
                ("citations", models.PositiveIntegerField(default=0)),
                ("downloads", models.PositiveIntegerField(default=0)),
                ("pdf_url", models.URLField(blank=True)),
                ("external_url", models.URLField()),
                (
                    "pakistani_institutions",
                    models.TextField(help_text="Institutions of Pakistani authors"),
                ),
                (
                    "pakistan_focused",
                    models.BooleanField(
                        default=False, help_text="Research focused on Pakistan"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pakistani_authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "academic_publications",
                "ordering": ["-year"],
                "indexes": [
                    models.Index(
                        fields=["discipline", "-year"],
                        name="academic_pu_discipl_b370c8_idx",
                    ),
                    models.Index(
                        fields=["-citations"], name="academic_pu_citatio_9f613d_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="researchsupervisor",
            index=models.Index(
                fields=["university", "discipline"],
                name="academic_re_univers_696f16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="researchsupervisor",
            index=models.Index(
                fields=["accepting_students"], name="academic_re_accepti_156d0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thesistopic",
            index=models.Index(
                fields=["discipline", "degree_level"],
                name="academic_th_discipl_d5f3ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="thesistopic",
            index=models.Index(
                fields=["university"], name="academic_th_univers_072e62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thesistopic",
            index=models.Index(
                fields=["-completion_year"], name="academic_th_complet_ecb8fb_idx"
            ),
        ),
    ]
