# Generated by Django 5.0.14 on 2025-11-09 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CofounderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "background_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical/Engineering"),
                            ("business", "Business/Management"),
                            ("designer", "Design/UX"),
                            ("domain_expert", "Domain Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "expertise",
                    models.TextField(
                        help_text="Your areas of expertise (comma-separated)"
                    ),
                ),
                ("years_of_experience", models.PositiveIntegerField()),
                (
                    "current_status",
                    models.CharField(help_text="Current role/status", max_length=200),
                ),
                ("looking_for_cofounder", models.BooleanField(default=True)),
                (
                    "seeking_background",
                    models.TextField(
                        help_text="What type of co-founder are you looking for?"
                    ),
                ),
                (
                    "startup_stage",
                    models.CharField(
                        choices=[
                            ("idea", "Just an Idea"),
                            ("mvp", "Building MVP"),
                            ("launched", "Launched"),
                            ("growing", "Growing"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "industry_interests",
                    models.TextField(
                        help_text="Industries of interest (comma-separated)"
                    ),
                ),
                ("startup_idea_summary", models.TextField(blank=True)),
                (
                    "looking_for_equity_split",
                    models.CharField(
                        blank=True, help_text="e.g., '50/50', '60/40'", max_length=100
                    ),
                ),
                ("can_work_fulltime", models.BooleanField(default=False)),
                ("location_preference", models.CharField(max_length=100)),
                ("remote_ok", models.BooleanField(default=True)),
                ("bio", models.TextField()),
                (
                    "past_ventures",
                    models.TextField(
                        blank=True, help_text="Previous startup/business experience"
                    ),
                ),
                ("skills", models.TextField()),
                ("linkedin_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cofounder_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "business_cofounder_profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["background_type", "is_active"],
                        name="business_co_backgro_81b060_idx",
                    ),
                    models.Index(
                        fields=["startup_stage"], name="business_co_startup_97ea14_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FundingOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "funding_type",
                    models.CharField(
                        choices=[
                            ("grant", "Grant"),
                            ("competition", "Pitch Competition"),
                            ("accelerator", "Accelerator Program"),
                            ("investor", "Investor Funding Round"),
                            ("government", "Government Fund"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("provider", models.CharField(max_length=200)),
                (
                    "amount",
                    models.CharField(
                        help_text="Funding amount available", max_length=100
                    ),
                ),
                ("equity_required", models.CharField(blank=True, max_length=100)),
                ("eligibility_criteria", models.TextField()),
                (
                    "target_industries",
                    models.TextField(help_text="Comma-separated industries"),
                ),
                ("startup_stage_required", models.CharField(max_length=100)),
                ("location_requirement", models.CharField(blank=True, max_length=200)),
                ("application_open_date", models.DateField()),
                ("application_deadline", models.DateField()),
                ("decision_date", models.DateField(blank=True, null=True)),
                ("application_url", models.URLField()),
                ("application_process", models.TextField()),
                ("required_materials", models.TextField()),
                ("website", models.URLField()),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "pakistan_friendly",
                    models.BooleanField(
                        default=True, help_text="Open to Pakistani startups"
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicants_interested",
                    models.ManyToManyField(
                        blank=True,
                        related_name="interested_funding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Funding Opportunities",
                "db_table": "business_funding_opportunities",
                "ordering": ["application_deadline"],
                "indexes": [
                    models.Index(
                        fields=["funding_type"], name="business_fu_funding_0a7505_idx"
                    ),
                    models.Index(
                        fields=["application_deadline"],
                        name="business_fu_applica_27696a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegulatoryGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("business_registration", "Business Registration"),
                            ("tax", "Tax & Compliance"),
                            ("import_export", "Import/Export"),
                            ("intellectual_property", "IP & Patents"),
                            ("labor_law", "Labor Laws"),
                            ("engineering_practice", "Engineering Practice Act"),
                        ],
                        max_length=30,
                    ),
                ),
                ("summary", models.TextField()),
                ("detailed_guide", models.TextField()),
                ("step_by_step_process", models.TextField()),
                ("required_documents", models.TextField()),
                ("estimated_cost", models.CharField(blank=True, max_length=100)),
                ("estimated_timeline", models.CharField(blank=True, max_length=100)),
                (
                    "relevant_authorities",
                    models.TextField(help_text="Which government bodies are involved?"),
                ),
                ("authority_contacts", models.TextField(blank=True)),
                (
                    "official_links",
                    models.TextField(blank=True, help_text="Official government links"),
                ),
                (
                    "downloadable_forms",
                    models.FileField(blank=True, upload_to="regulatory/forms/"),
                ),
                ("last_verified_date", models.DateField()),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regulatory_guides_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "business_regulatory_guides",
                "ordering": ["category", "title"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="business_re_categor_5a6de7_idx"
                    ),
                    models.Index(fields=["slug"], name="business_re_slug_6beffa_idx"),
                ],
            },
        ),
    ]
