# Generated by Django 5.0.14 on 2025-11-10 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("announcement", "Announcement"),
                            ("insight", "Industry Insight"),
                            ("discussion", "Discussion"),
                            ("job", "Job Posting"),
                            ("event", "Event"),
                        ],
                        default="discussion",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("external_link", models.URLField(blank=True)),
                (
                    "topics",
                    models.JSONField(default=list, help_text="List of relevant topics"),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_feed_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_feed_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="feed.feedpost",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("association", "Professional Association"),
                            ("company", "Company"),
                            ("university", "University"),
                            ("government", "Government Body"),
                            ("startup", "Startup"),
                            ("ngo", "NGO/Non-Profit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organizations/"
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("follower_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="managed_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Professional Bodies",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="feedpost",
            name="author_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_posts",
                to="feed.professionalbody",
            ),
        ),
        migrations.CreateModel(
            name="ThoughtLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., Senior Software Engineer, CEO", max_length=200
                    ),
                ),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField()),
                (
                    "expertise_areas",
                    models.JSONField(default=list, help_text="List of expertise areas"),
                ),
                ("verified", models.BooleanField(default=False)),
                ("follower_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thought_leader_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-follower_count"],
            },
        ),
        migrations.CreateModel(
            name="TopicSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("general", "General Engineering"),
                            ("career", "Career Development"),
                            ("technical", "Technical Discussions"),
                            ("industry", "Industry News"),
                            ("academia", "Academia & Research"),
                            ("startups", "Startups & Entrepreneurship"),
                            ("jobs", "Job Opportunities"),
                            ("scholarships", "Scholarships"),
                            ("software", "Software Engineering"),
                            ("civil", "Civil Engineering"),
                            ("electrical", "Electrical Engineering"),
                            ("mechanical", "Mechanical Engineering"),
                            ("chemical", "Chemical Engineering"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thought_leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="feed.thoughtleader",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="feed.professionalbody",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("subscriber", "organization")},
            },
        ),
        migrations.AddIndex(
            model_name="feedpost",
            index=models.Index(
                fields=["-created_at"], name="feed_feedpo_created_3b2746_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedpost",
            index=models.Index(
                fields=["post_type"], name="feed_feedpo_post_ty_9591a0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="topicsubscription",
            unique_together={("subscriber", "topic")},
        ),
        migrations.AlterUniqueTogether(
            name="usersubscription",
            unique_together={("subscriber", "thought_leader")},
        ),
    ]
