# Generated by Django 5.0.14 on 2025-11-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionalbody",
            name="category",
            field=models.CharField(
                choices=[
                    ("association", "Professional Association"),
                    ("company", "Company"),
                    ("university", "University"),
                    ("government", "Government Body"),
                    ("startup", "Startup"),
                    ("ngo", "NGO/Non-Profit"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="professionalbody",
            name="verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="thoughtleader",
            name="verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
