# Generated by Django 5.0.14 on 2025-11-12 08:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official company name",
                        max_length=200,
                        unique=True,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL Slug"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company_logos/",
                        verbose_name="Company Logo",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("software", "Software Development"),
                            ("telecom", "Telecommunications"),
                            ("finance", "Finance & Banking"),
                            ("manufacturing", "Manufacturing"),
                            ("consulting", "Consulting"),
                            ("education", "Education"),
                            ("healthcare", "Healthcare"),
                            ("energy", "Energy & Utilities"),
                            ("construction", "Construction & Engineering"),
                            ("retail", "Retail & E-commerce"),
                            ("transportation", "Transportation & Logistics"),
                            ("government", "Government & Public Sector"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Industry",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("1-10", "1-10 employees"),
                            ("11-50", "11-50 employees"),
                            ("51-200", "51-200 employees"),
                            ("201-500", "201-500 employees"),
                            ("501-1000", "501-1000 employees"),
                            ("1001-5000", "1001-5000 employees"),
                            ("5001+", "5000+ employees"),
                        ],
                        max_length=20,
                        verbose_name="Company Size",
                    ),
                ),
                (
                    "headquarters_location",
                    models.CharField(
                        help_text="City and country of headquarters",
                        max_length=200,
                        verbose_name="Headquarters Location",
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1800),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Founded Year",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Company Website"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Overview of the company and what they do",
                        verbose_name="Company Description",
                    ),
                ),
                (
                    "overall_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Average rating from all reviews",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Overall Rating",
                    ),
                ),
                (
                    "recommend_to_friend_percentage",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Percentage of employees who recommend this company",
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Recommend to Friend %",
                    ),
                ),
                (
                    "ceo_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="CEO Name"
                    ),
                ),
                (
                    "ceo_approval_rating",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Percentage of employees who approve of the CEO",
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="CEO Approval Rating",
                    ),
                ),
                (
                    "total_reviews_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Reviews"
                    ),
                ),
                (
                    "total_salaries_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Salaries"
                    ),
                ),
                (
                    "total_interviews_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Interviews"
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Company profile verified by admin",
                        verbose_name="Verified Company",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["-overall_rating", "name"],
                "indexes": [
                    models.Index(
                        fields=["industry", "-overall_rating"],
                        name="companies_c_industr_179de3_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="companies_c_created_a89ef1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "benefit_category",
                    models.CharField(
                        choices=[
                            ("health", "Health & Wellness"),
                            ("insurance", "Insurance"),
                            ("retirement", "Retirement & Savings"),
                            ("pto", "Paid Time Off"),
                            ("perks", "Office Perks"),
                            ("professional_development", "Professional Development"),
                            ("family", "Family & Parenting"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Benefit Category",
                    ),
                ),
                (
                    "benefit_name",
                    models.CharField(
                        help_text="e.g., 'Health Insurance', 'Remote Work', '401k Matching'",
                        max_length=200,
                        verbose_name="Benefit Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Details about this benefit",
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Benefit",
                "verbose_name_plural": "Company Benefits",
                "ordering": ["benefit_category", "benefit_name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="company_photos/", verbose_name="Photo"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Caption"
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("office", "Office"),
                            ("team", "Team"),
                            ("event", "Event"),
                            ("culture", "Culture"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                        verbose_name="Photo Type",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Photo approved for display by admin",
                        verbose_name="Approved",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_company_photos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Photo",
                "verbose_name_plural": "Company Photos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "-created_at"],
                        name="companies_c_company_1c806e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("current", "Current Employee"),
                            ("former", "Former Employee"),
                        ],
                        max_length=20,
                        verbose_name="Employment Status",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        help_text="Your role at the company",
                        max_length=200,
                        verbose_name="Job Title",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="City where you worked",
                        max_length=200,
                        verbose_name="Location",
                    ),
                ),
                (
                    "employment_length",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="How long you worked at the company",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Employment Length (Years)",
                    ),
                ),
                (
                    "overall_rating",
                    models.PositiveIntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Overall Rating",
                    ),
                ),
                (
                    "work_life_balance_rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Work-Life Balance",
                    ),
                ),
                (
                    "culture_values_rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Culture & Values",
                    ),
                ),
                (
                    "career_opportunities_rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Career Opportunities",
                    ),
                ),
                (
                    "compensation_benefits_rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Compensation & Benefits",
                    ),
                ),
                (
                    "senior_management_rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Senior Management",
                    ),
                ),
                (
                    "review_title",
                    models.CharField(
                        help_text="Brief summary of your experience",
                        max_length=200,
                        verbose_name="Review Title",
                    ),
                ),
                (
                    "pros",
                    models.TextField(
                        help_text="What are the positives about working at this company?",
                        verbose_name="Pros",
                    ),
                ),
                (
                    "cons",
                    models.TextField(
                        help_text="What are the negatives or areas for improvement?",
                        verbose_name="Cons",
                    ),
                ),
                (
                    "advice_to_management",
                    models.TextField(
                        blank=True,
                        help_text="What would you suggest management do to improve?",
                        verbose_name="Advice to Management",
                    ),
                ),
                (
                    "recommend_to_friend",
                    models.BooleanField(
                        default=True, verbose_name="Would Recommend to Friend"
                    ),
                ),
                (
                    "ceo_approval",
                    models.BooleanField(
                        blank=True,
                        help_text="Do you approve of the CEO's leadership?",
                        null=True,
                        verbose_name="Approve of CEO",
                    ),
                ),
                (
                    "helpful_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Helpful Count"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Review approved for display",
                        verbose_name="Approved",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glassdoor_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "helpful_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="helpful_company_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Users who found this helpful",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Review",
                "verbose_name_plural": "Company Reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "-created_at"],
                        name="companies_c_company_c4b335_idx",
                    ),
                    models.Index(
                        fields=["company", "-overall_rating"],
                        name="companies_c_company_758e6e_idx",
                    ),
                ],
                "unique_together": {("company", "author")},
            },
        ),
        migrations.CreateModel(
            name="SalaryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Job Title"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="City where the job is based",
                        max_length=200,
                        verbose_name="Location",
                    ),
                ),
                (
                    "experience_years",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Years of Experience",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("bachelors", "Bachelor's Degree"),
                            ("masters", "Master's Degree"),
                            ("phd", "PhD"),
                            ("diploma", "Diploma"),
                            ("no_degree", "No Degree"),
                        ],
                        max_length=20,
                        verbose_name="Education Level",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="Employment Type",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("PKR", "Pakistani Rupee"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                        ],
                        default="PKR",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual base salary",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Base Salary (Annual)",
                    ),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Annual Bonus",
                    ),
                ),
                (
                    "additional_compensation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Stock, commissions, etc.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Additional Compensation",
                    ),
                ),
                (
                    "total_compensation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total Annual Compensation",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Salary verified by admin",
                        verbose_name="Verified",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaries",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional - can be anonymous",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Report",
                "verbose_name_plural": "Salary Reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "job_title"],
                        name="companies_s_company_e27f7e_idx",
                    ),
                    models.Index(
                        fields=["company", "-created_at"],
                        name="companies_s_company_514a6b_idx",
                    ),
                ],
            },
        ),
    ]
