# Generated by Django 5.0.14 on 2025-11-09 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("industry", models.CharField(max_length=100)),
                ("headquarters", models.CharField(max_length=100)),
                (
                    "pakistan_locations",
                    models.TextField(
                        help_text="Cities where company has offices in Pakistan"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("startup", "1-50 employees"),
                            ("small", "51-200 employees"),
                            ("medium", "201-1000 employees"),
                            ("large", "1000+ employees"),
                        ],
                        max_length=20,
                    ),
                ),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("website", models.URLField()),
                ("description", models.TextField()),
                (
                    "tech_stack",
                    models.TextField(
                        blank=True, help_text="Technologies used (comma-separated)"
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="companies/logos/")),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Company Profiles",
                "db_table": "networking_company_profiles",
                "indexes": [
                    models.Index(fields=["name"], name="networking__name_fe9203_idx"),
                    models.Index(
                        fields=["industry"], name="networking__industr_176608_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("conference", "Conference"),
                            ("webinar", "Webinar"),
                            ("workshop", "Workshop"),
                            ("meetup", "Meetup"),
                            ("career_fair", "Career Fair"),
                            ("hackathon", "Hackathon"),
                            ("seminar", "Seminar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("organizer", models.CharField(max_length=200)),
                (
                    "discipline",
                    models.CharField(
                        blank=True,
                        help_text="Relevant engineering discipline",
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("timezone", models.CharField(default="Asia/Karachi", max_length=50)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("in_person", "In-Person"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="For in-person events", max_length=200
                    ),
                ),
                (
                    "online_link",
                    models.URLField(blank=True, help_text="For online events"),
                ),
                ("registration_required", models.BooleanField(default=True)),
                ("registration_url", models.URLField(blank=True)),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fee in PKR (0 for free)",
                        max_digits=10,
                    ),
                ),
                ("max_attendees", models.PositiveIntegerField(blank=True, null=True)),
                ("featured", models.BooleanField(default=False)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "networking_events",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("attended", models.BooleanField(default=False)),
                ("feedback", models.TextField(blank=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="networking.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "networking_event_attendance",
                "unique_together": {("event", "user")},
            },
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                related_name="events_attending",
                through="networking.EventAttendance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AlumniProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university", models.CharField(max_length=200)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("bs", "Bachelor of Science"),
                            ("ms", "Master of Science"),
                            ("phd", "Doctor of Philosophy"),
                            ("diploma", "Diploma"),
                        ],
                        max_length=20,
                    ),
                ),
                ("discipline", models.CharField(max_length=100)),
                ("graduation_year", models.PositiveIntegerField()),
                ("current_position", models.CharField(blank=True, max_length=200)),
                ("current_company", models.CharField(blank=True, max_length=200)),
                (
                    "location",
                    models.CharField(help_text="Current city/country", max_length=100),
                ),
                (
                    "willing_to_help",
                    models.BooleanField(
                        default=True, help_text="Willing to help current students?"
                    ),
                ),
                (
                    "help_areas",
                    models.TextField(
                        blank=True,
                        help_text="What can you help with? (Career advice, referrals, etc.)",
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "networking_alumni_profiles",
                "indexes": [
                    models.Index(
                        fields=["university", "graduation_year"],
                        name="networking__univers_883d61_idx",
                    ),
                    models.Index(
                        fields=["discipline"], name="networking__discipl_78c9bf_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=100)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("current", "Current Employee"),
                            ("former", "Former Employee"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "duration_months",
                    models.PositiveIntegerField(
                        help_text="How long did you work there?"
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "work_life_balance",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "compensation",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "culture",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "career_growth",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "management",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("pros", models.TextField()),
                ("cons", models.TextField()),
                ("advice_to_management", models.TextField(blank=True)),
                (
                    "engineering_specific_feedback",
                    models.TextField(
                        blank=True, help_text="Technical environment, tools, processes"
                    ),
                ),
                ("would_recommend", models.BooleanField()),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("verified_employee", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="networking.companyprofile",
                    ),
                ),
            ],
            options={
                "db_table": "networking_company_reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "-overall_rating"],
                        name="networking__company_eaef43_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="networking__created_0fad14_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["start_date"], name="networking__start_d_ba8be0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type"], name="networking__event_t_33c905_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["format"], name="networking__format_5fafdd_idx"),
        ),
    ]
