# Generated by Django 5.0.14 on 2025-11-08 10:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UniversityProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university_name", models.CharField(max_length=200)),
                ("program_name", models.CharField(max_length=200)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("BS", "BS"),
                            ("MS", "MS"),
                            ("PhD", "PhD"),
                            ("Diploma", "Diploma"),
                        ],
                        max_length=20,
                    ),
                ),
                ("discipline", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("accreditation", models.JSONField(default=list)),
                ("duration", models.CharField(max_length=50)),
                ("overview", models.TextField()),
                ("pros", models.JSONField(default=list)),
                ("cons", models.JSONField(default=list)),
                (
                    "employability_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("research_opportunities", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["university_name", "program_name"],
                "unique_together": {("university_name", "program_name", "degree")},
            },
        ),
        migrations.CreateModel(
            name="ProgramReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("content", models.TextField()),
                ("graduation_year", models.CharField(blank=True, max_length=4)),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="universities.universityprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("program", "author")},
            },
        ),
    ]
