# Generated by Django 5.0.14 on 2025-11-09 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EngineeringCalculator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("discipline", models.CharField(max_length=100)),
                (
                    "calculator_type",
                    models.CharField(
                        help_text="e.g., 'Beam Calculator', 'Power Factor Calculator'",
                        max_length=100,
                    ),
                ),
                (
                    "formula_info",
                    models.TextField(help_text="Mathematical formula and explanation"),
                ),
                ("usage_instructions", models.TextField()),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tools_calculators",
                "ordering": ["-usage_count"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareDirectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        help_text="e.g., 'CAD', 'Simulation', 'Project Management'",
                        max_length=100,
                    ),
                ),
                ("discipline", models.CharField(max_length=100)),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("freemium", "Freemium"),
                            ("paid", "Paid"),
                            ("subscription", "Subscription"),
                            ("student_free", "Free for Students"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price_info",
                    models.TextField(blank=True, help_text="Pricing details"),
                ),
                (
                    "platforms",
                    models.CharField(
                        help_text="Windows, Mac, Linux, Web (comma-separated)",
                        max_length=100,
                    ),
                ),
                ("system_requirements", models.TextField(blank=True)),
                ("website", models.URLField()),
                ("download_link", models.URLField(blank=True)),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("available_in_pakistan", models.BooleanField(default=True)),
                (
                    "local_vendor",
                    models.CharField(
                        blank=True, help_text="Local vendor in Pakistan", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Software Directories",
                "db_table": "tools_software_directory",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="tools_softw_categor_4b3c5f_idx"
                    ),
                    models.Index(
                        fields=["discipline"], name="tools_softw_discipl_53e1ff_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EquipmentListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("sell", "For Sale"),
                            ("rent", "For Rent"),
                            ("wanted", "Wanted to Buy/Rent"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="e.g., 'Lab Equipment', 'Tools', 'Instruments', 'Books'",
                        max_length=100,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("like_new", "Like New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in PKR", max_digits=10
                    ),
                ),
                ("negotiable", models.BooleanField(default=True)),
                ("location", models.CharField(max_length=100)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("images", models.ImageField(blank=True, upload_to="equipment/")),
                ("is_active", models.BooleanField(default=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tools_equipment_listings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["listing_type", "is_active"],
                        name="tools_equip_listing_8bca5c_idx",
                    ),
                    models.Index(
                        fields=["location"], name="tools_equip_locatio_e8b1dd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReferenceLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("handbook", "Handbook"),
                            ("standard", "Standard/Code"),
                            ("paper", "Research Paper"),
                            ("tutorial", "Tutorial"),
                            ("video", "Video"),
                            ("book", "Book"),
                        ],
                        max_length=20,
                    ),
                ),
                ("discipline", models.CharField(max_length=100)),
                ("topics", models.TextField(help_text="Comma-separated topics")),
                ("url", models.URLField(blank=True)),
                ("file", models.FileField(blank=True, upload_to="references/")),
                ("is_free", models.BooleanField(default=True)),
                ("author", models.CharField(blank=True, max_length=200)),
                (
                    "publication_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("language", models.CharField(default="English", max_length=50)),
                ("downloads", models.PositiveIntegerField(default=0)),
                ("rating_sum", models.PositiveIntegerField(default=0)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_references",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reference Libraries",
                "db_table": "tools_reference_library",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["discipline"], name="tools_refer_discipl_b69f17_idx"
                    ),
                    models.Index(
                        fields=["resource_type"], name="tools_refer_resourc_0f80f9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SoftwareReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("review", models.TextField()),
                ("pros", models.TextField()),
                ("cons", models.TextField()),
                ("use_case", models.TextField(help_text="What did you use it for?")),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="software_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="tools.softwaredirectory",
                    ),
                ),
            ],
            options={
                "db_table": "tools_software_reviews",
                "ordering": ["-created_at"],
                "unique_together": {("software", "reviewer")},
            },
        ),
    ]
