# Generated by Django 5.0.14 on 2025-11-09 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("contribution", "Contribution"),
                            ("expertise", "Expertise"),
                            ("milestone", "Milestone"),
                            ("special", "Special"),
                        ],
                        max_length=30,
                    ),
                ),
                ("criteria", models.TextField(help_text="How to earn this badge")),
                ("points_value", models.PositiveIntegerField(default=10)),
                ("icon", models.ImageField(blank=True, upload_to="badges/")),
                ("color", models.CharField(default="blue", max_length=20)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("times_awarded", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "gamification_badges",
                "ordering": ["rarity", "name"],
            },
        ),
        migrations.CreateModel(
            name="ChallengeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_text", models.TextField()),
                (
                    "submission_file",
                    models.FileField(blank=True, upload_to="challenge_submissions/"),
                ),
                ("submission_url", models.URLField(blank=True)),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                ("is_winner", models.BooleanField(default=False)),
                ("feedback", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upvotes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="challenge_upvotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gamification_challenge_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("all_time", "All Time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "top_users_data",
                    models.JSONField(help_text="Cached leaderboard data"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "gamification_leaderboards",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["period_type", "-period_start"],
                        name="gamificatio_period__9413ca_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReputationScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                (
                    "reputation_level",
                    models.CharField(
                        choices=[
                            ("newcomer", "Newcomer"),
                            ("member", "Member"),
                            ("contributor", "Contributor"),
                            ("expert", "Expert"),
                            ("guru", "Guru"),
                            ("legend", "Legend"),
                        ],
                        default="newcomer",
                        max_length=20,
                    ),
                ),
                ("posts_created", models.PositiveIntegerField(default=0)),
                ("replies_posted", models.PositiveIntegerField(default=0)),
                ("helpful_votes_received", models.PositiveIntegerField(default=0)),
                ("best_answers", models.PositiveIntegerField(default=0)),
                ("resources_shared", models.PositiveIntegerField(default=0)),
                ("projects_showcased", models.PositiveIntegerField(default=0)),
                ("reviews_written", models.PositiveIntegerField(default=0)),
                ("consecutive_days_active", models.PositiveIntegerField(default=0)),
                ("last_active_date", models.DateField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gamification_reputation_scores",
            },
        ),
        migrations.CreateModel(
            name="WeeklyChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Problem"),
                            ("design", "Design Challenge"),
                            ("trivia", "Engineering Trivia"),
                            ("code_review", "Code Review"),
                        ],
                        max_length=30,
                    ),
                ),
                ("problem_statement", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=20,
                    ),
                ),
                ("discipline", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("points_reward", models.PositiveIntegerField(default=50)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge_reward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gamification.badge",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="challenges_joined",
                        through="gamification.ChallengeSubmission",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gamification_weekly_challenges",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="challengesubmission",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="gamification.weeklychallenge",
            ),
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                ("display_on_profile", models.BooleanField(default=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="gamification.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges_earned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gamification_user_badges",
                "ordering": ["-earned_at"],
                "unique_together": {("user", "badge")},
            },
        ),
        migrations.AddIndex(
            model_name="weeklychallenge",
            index=models.Index(
                fields=["-start_date"], name="gamificatio_start_d_08e5b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklychallenge",
            index=models.Index(
                fields=["challenge_type"], name="gamificatio_challen_a18fe3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="challengesubmission",
            unique_together={("challenge", "user")},
        ),
    ]
